import type { ActionRow, AlertRow, KpiRow, TrendRow } from './types';

export const mockKpis: KpiRow[] = [
  {
    declared_sales: 428_760_000,
    assessed_tax: 77_176_800,
    claimed_tax_credit: 51_940_000,
    high_risk_taxpayers: 18,
    exposure_amount: 12_840_500,
  },
];

export const mockAlerts: AlertRow[] = [
  {
    alert_id: 'a'.repeat(64),
    priority: 'CRITICAL',
    taxpayer_id: 'TP-10482',
    taxpayer_name: 'Distribuciones Andinas del Pacífico S.A.C.',
    ruc: '20604821937',
    segment: 'PRICO',
    region: 'Lima',
    economic_activity: 'Comercio mayorista',
    risk_score: 96,
    declared_sales: 8_420_000,
    third_party_sales: 11_180_000,
    sales_gap: 2_760_000,
    claimed_tax_credit: 1_940_000,
    credit_ratio: 1.28,
    amendment_count: 4,
    signal_count: 5,
    primary_signal: 'Brecha con ventas informadas por terceros',
    recommended_action: 'OPEN_INVESTIGATION',
    evidence_summary: 'Ventas de terceros superan lo declarado en 32.8%; cuatro rectificatorias en 90 días.',
  },
  {
    alert_id: 'b'.repeat(64),
    priority: 'CRITICAL',
    taxpayer_id: 'TP-08711',
    taxpayer_name: 'Servicios Logísticos Norte E.I.R.L.',
    ruc: '20578163429',
    segment: 'Mediana empresa',
    region: 'La Libertad',
    economic_activity: 'Transporte de carga',
    risk_score: 91,
    declared_sales: 3_180_000,
    third_party_sales: 4_090_000,
    sales_gap: 910_000,
    claimed_tax_credit: 842_000,
    credit_ratio: 1.41,
    amendment_count: 2,
    signal_count: 4,
    primary_signal: 'Crédito fiscal atípico para el segmento',
    recommended_action: 'REQUEST_CLARIFICATION',
    evidence_summary: 'Ratio de crédito fiscal 41% sobre su referencia sectorial y proveedores con baja recurrencia.',
  },
  {
    alert_id: 'c'.repeat(64),
    priority: 'HIGH',
    taxpayer_id: 'TP-06204',
    taxpayer_name: 'Inversiones Amazónicas Verde S.R.L.',
    ruc: '20496715384',
    segment: 'Pequeña empresa',
    region: 'Loreto',
    economic_activity: 'Materiales de construcción',
    risk_score: 83,
    declared_sales: 1_760_000,
    third_party_sales: 2_210_000,
    sales_gap: 450_000,
    claimed_tax_credit: 338_000,
    credit_ratio: 0.94,
    amendment_count: 3,
    signal_count: 3,
    primary_signal: 'Rectificatorias recurrentes',
    recommended_action: 'REQUEST_CLARIFICATION',
    evidence_summary: 'Tres rectificatorias consecutivas elevaron el crédito fiscal y redujeron ventas declaradas.',
  },
  {
    alert_id: 'd'.repeat(64),
    priority: 'MEDIUM',
    taxpayer_id: 'TP-03198',
    taxpayer_name: 'Textiles del Sur Peruano S.A.C.',
    ruc: '20601987541',
    segment: 'Mediana empresa',
    region: 'Arequipa',
    economic_activity: 'Manufactura textil',
    risk_score: 68,
    declared_sales: 5_340_000,
    third_party_sales: 5_510_000,
    sales_gap: 170_000,
    claimed_tax_credit: 704_000,
    credit_ratio: 0.82,
    amendment_count: 1,
    signal_count: 2,
    primary_signal: 'Variación intermensual inusual',
    recommended_action: 'DISMISS',
    evidence_summary: 'Variación concentrada en campaña estacional; brecha acotada y consistente con el sector.',
  },
];

export const mockTrend: TrendRow[] = Array.from({ length: 14 }, (_, index) => ({
  event_date: new Date(Date.now() - (13 - index) * 86_400_000)
    .toISOString()
    .slice(0, 10),
  declared_sales: 11_800_000 + index * 285_000 + (index % 3) * 510_000,
  assessed_tax: 2_124_000 + index * 51_300,
}));

export const mockActions: ActionRow[] = [
  {
    action_id: '4a93d12a-719d-4e36-a6cd-90e509964145',
    alert_id: 'z'.repeat(64),
    decision_type: 'OPEN_INVESTIGATION',
    status: 'OPEN',
    assignee: 'fiscalizacion@sunat.gob.pe',
    notes: 'Revisar sustentos de compras y cruces con comprobantes de terceros.',
    priority: 'CRITICAL',
    taxpayer_id: 'TP-10482',
    taxpayer_name: 'Distribuciones Andinas del Pacífico S.A.C.',
    ruc: '20604821937',
    risk_score: 96,
    created_by: 'analista@sunat.gob.pe',
    created_at: new Date(Date.now() - 35 * 60_000).toISOString(),
    due_at: new Date(Date.now() + 23 * 3_600_000).toISOString(),
    is_overdue: false,
  },
];
