command: ['npm', 'run', 'start']
env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom: genie-space
  - name: GOLD_QUEUE_TABLE
    valueFrom: table
  - name: GOLD_METRIC_VIEW
    valueFrom: table-3
  - name: OPS_ACTIONS_TABLE
    valueFrom: table-2
